# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-26 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purposeobjecttranslation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='A Unique identifier for the category'),
        ),
    ]
