# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0002_auto_20181126_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookie',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
