# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0002_add_default_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiecontrol',
            name='closeStyle',
            field=models.CharField(blank=True, choices=[('icon', 'icon'), ('labelled', 'labelled'), ('button', 'button')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='initialState',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed'), ('notify', 'notify')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='layout',
            field=models.CharField(blank=True, choices=[('slideout', 'slideout'), ('popup', 'popup')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='position',
            field=models.CharField(blank=True, choices=[('LEFT', 'LEFT'), ('RIGHT', 'RIGHT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='product',
            field=models.CharField(choices=[('COMMUNITY', 'COMMUNITY'), ('PRO', 'PRO'), ('PRO_MULTISITE', 'PRO_MULTISITE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='theme',
            field=models.CharField(blank=True, choices=[('LIGHT', 'LIGHT'), ('DARK', 'DARK')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='toggleType',
            field=models.CharField(blank=True, choices=[('slider', 'slider'), ('checkbox', 'checkbox')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purposeobject',
            name='lawfulBasis',
            field=models.CharField(blank=True, choices=[('consent', 'Consent'), ('legitimate interest', 'Legitimate Interest')], help_text='requires explicit user consent', max_length=255, null=True),
        ),
    ]
