# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-19 16:56
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import parler.fields


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0003_auto_20190606_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookie',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='thirdpartycookie',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='purposeobjecttranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='django_cookie_control.PurposeObject'),
        ),
        migrations.AlterField(
            model_name='statementtranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='django_cookie_control.Statement'),
        ),
        migrations.AlterField(
            model_name='textvaluetranslation',
            name='master',
            field=parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='django_cookie_control.TextValue'),
        ),
    ]
