# Generated by Django 3.0.5 on 2020-04-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0005_auto_20200131_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiecontrol',
            name='initialState',
            field=models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed'), ('notify', 'notify'), ('top', 'top')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='position',
            field=models.CharField(blank=True, choices=[('left', 'LEFT'), ('right', 'RIGHT')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cookiecontrol',
            name='theme',
            field=models.CharField(blank=True, choices=[('light', 'LIGHT'), ('dark', 'DARK')], max_length=255, null=True),
        ),
    ]
