# Generated by Django 2.2.14 on 2020-08-20 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0007_auto_20200820_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iabtexttranslation',
            old_name='panelIntro',
            new_name='panelIntro1',
        ),
    ]
