# Generated by Django 2.2.16 on 2020-09-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0009_auto_20200821_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiecontrol',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
