# Generated by Django 2.2.16 on 2020-09-04 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_cookie_control', '0010_cookiecontrol_is_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookiecontrol',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
    ]
